### PR TITLE
Search multiple tabs

### PR DESCRIPTION
**Pull request by Messius58**
https://user-images.githubusercontent.com/59862077/103172099-572f2800-4894-11eb-9f58-0536f6fdcb74.mp4

Hi,

I modified the sources on the devel branch for implemented the capability of search on all tabs opened.
The files that are modified mainly Node, MainWindow and connection.

### CODE REVIEW

**Review by phase1geo — COMMENTED** [review]
We need to add some contextual information to the search results.  Previously, we displayed what type of element was matched against the search text:  connection/node and title/note.  I believe this information should continue to be displayed.

In addition, if we are searching over multiple tabs, we need to add information as to which tab matches the result, displaying all matches in the current tab first.

It might make sense to make multiple tab search a selectable feature in the search popup.  By default, search the current tab only, but make a switch or radio-style menubutton that allows the user to select whether the current tab or all tabs are to be searched.

Functionally, this pull request seems to work well, but I think we need to enhance the interface before this can be committed to the master branch.

**Comment by phase1geo** [comment]
Additionally, is there a reason why notes are no longer being searched?

**Comment by Messius58** [comment]
Anything good reason, just if forgot this part, sorry.
I have restored and tested with an example file which is in the tests folder.
I commented the export because don't compile, the function (callback ?) is missing.

**Comment by phase1geo** [comment]
I would like to make a few changes to this implementation, but I will do that to my local copy of this branch before merging it into the devel branch.  I'll do this apart from the pull request on GitHub as I don't know how to change the branch being merged into (from master to devel within GitHub).

**Comment by phase1geo** [comment]
I figured out how to pull the request into the devel branch, so I have gone ahead and merged these changes into devel.  I will create a new branch to make the UI modifications.

Thank for for looking into this feature!

**Pull request merged**
