### PR TITLE
Create It.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by albanobattistella** [comment]
> Looks like there are a few syntax errors with this file. Line 1007 has a period (.) character outside of a string. I believe the Travis CI build process is also complaining about line 667 and 678 although I don't know what the issue with these lines is.
> 
> Can you take a look?

Hi,
I fixed line 1007. I checked the other but I've not found any issue.

**Comment by albanobattistella** [comment]
> Line 678 uses a "msgid" keyword when it should be a "msgstr". I think that is the only line remaining to be fixed.

Done!

**Comment by phase1geo** [comment]
Looks good! Thank you for your contribution!

**Comment by albanobattistella** [comment]
> Looks good! Thank you for your contribution!

Thanks to you for your great work!

**Pull request merged**
